name: Deploy via ftp
on: push: branches:
        - main
jobs:
deploy:
    name: Deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: FTP Deploy Locaweb
    uses: locaweb/ftp-deploy@1.0.0
    with:
        host: ${{ secrets.hosttop }} 
        user: ${{ secrets.usertop }}
        password: ${{ secrets.passtop }}
        localDir: "web"
  