name: Deploy via ftp
on: 
  push:
    branches: [ master ]
jobs:
        deploy:
          name: Deploy
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v2

          - name: FTP Deploy Locaweb
            uses: locaweb/ftp-deploy@1.0.0
            with:
              host: ${{ secrets.hosttop }} 
              user: ${{ secrets.usertop }}
              password: ${{ secrets.passtop }}
              remoteDir: "web"
